// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ycbpskzeuqsurwodpnni.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InljYnBza3pldXFzdXJ3b2Rwbm5pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MTY5MzcsImV4cCI6MjA3MzA5MjkzN30.qeAakh95WVRELiU44lkmxk4ljvECxhkzyPRz6LZ2xts";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);